# Generated by Django 5.2.6 on 2025-09-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PR_NAME', models.CharField(max_length=250)),
                ('PR_PRICE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PR_Available', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
