# Generated by Django 5.2.6 on 2025-09-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='PR_Available',
            new_name='PR_AVAILABLE',
        ),
    ]
