# Generated by Django 5.2.6 on 2025-09-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsApp', '0002_rename_pr_available_product_pr_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PR_PRICE',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
